### ISSUE TITLE
Typo in Main repositories

### ISSUE THREAD

**Issue by donatogomez** [zero-os/home#54]
Just a typo on the documentation in the part that said RESTfull, is only one "L"
Right way: RESTful
![image](https://cloud.githubusercontent.com/assets/14346541/26680678/a8432508-46da-11e7-84cf-bc428285938c.png)

**Comment by zaibon** [comment]
fixed by https://github.com/zero-os/home/commit/e64f2b204bbff18fe39c7f6c4e5b887788bad73c
