### ISSUE TITLE
vdisk boot images (templates) come from FTP server

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#64]
- images are exported boot disks to an FTP server
- zero-os gets method to import image from FTP server to deduped disk
- deduped disks go to 4 kbyte block size again
- when setting up new environment
   - users specify which images to import
   - arguments
        - ftp unc path: ftp://user@host:port/images/imagepath 
        - encr key if used by restic
- restic is used for export/import so we have dedupe, which means there can be multiple versions of the same image 
- the result is a deduped boot disk

**Comment by despiegk** [comment]
we realize that more data will be downloaded (non dedupe) but at backend its still deduped. But advantages are lot less code & more simplicity.

**Comment by zaibon** [comment]
Restic recommand not to use FTP: see https://github.com/zero-os/home/issues/65#issuecomment-313683922

**Comment by rkhamis** [comment]
Duplicate of https://github.com/zero-os/0-orchestrator/issues/556
