### ISSUE TITLE
export/import to ftp server of vdisks & containers

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#65]
- use restic for containers our own lib for vdisks
- when container
   - backup full filesystem, restic should take care of metadata of files
- when vdisk
   - read over lba range (used items only)
   - per std 128 kb block upload using ftp with dedupe (see ...)
   - blocksize is configurable 
- implement export & import
- export & import can go from dedupe to non dedupe and other way around
    - need to specify type of vdisk when doing restore

**Comment by despiegk** [comment]
this will be to generic FTP server first (not the 0-OS enabled one yet)

**Comment by despiegk** [comment]
needs to be primitive function in Zero-OS

**Comment by despiegk** [comment]
requires vm to be stopped

**Comment by zaibon** [comment]
@despiegk  can you check this FR https://github.com/zero-os/0-Disk/issues/296

Also restic doesn't recommand to use FTP cause it's really slow.
Instead they have a rest server available, they also created a caddy plugin for it so we could reuse that directly. (https://github.com/restic/rest-server , https://github.com/restic/caddy)

**Comment by despiegk** [comment]
see https://github.com/zero-os/0-Disk/issues/317
see https://github.com/zero-os/0-orchestrator/issues/664

**Comment by FastGeert** [comment]
To be continued in the other issues
