### ISSUE TITLE
0-stor implementation v 1.0 beta (server & client)

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#67]
- all in golang using mainly grpc
- will be used in
   - backend for ftp which is backend for restic which is used in export/import
   - backend for tlog server in 0-disk
   - ftp which is our new hub (much more easy just some ftp links for restic)
- see corresponding repo's for more info

**Comment by zaibon** [comment]
Repo of 0-stor : https://github.com/zero-os/0-stor
