### ISSUE TITLE
Zero-OS HUB is using 0-stor-lib as backend

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#69]
advantages
- scalability
- redundancy (with repair)
- dedupe is part of 0-stor

how
- flists are stored on FTP server which lives on top of 0-stor
- files are directly stored in 0-stor

**Comment by rkhamis** [comment]
blocked on https://github.com/zero-os/0-hub/issues/18

**Comment by zaibon** [comment]
won't be needed, we'll go for a distributed hub instead
