### ISSUE TITLE
Zero-OS exported image on FTP to 0-HUB conversion method

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#70]
- method on HUB which takes restic ftp location with optional encr key for container
- rebuilds the flist & put on HUB (0-stor backend)
- registers the flist in the HUB on right location

advantages
- allows people to easily export their own modified containers to HUB over FTP 
- because of restic & 0-Stor there is full dedupe which means becomes very easy for people to create multiple versions.

**Comment by zaibon** [comment]
I'm not sure I fully understand. 
there is not export method for containers, only virtual machine.

**Comment by rkhamis** [comment]
Moved to https://github.com/zero-os/0-hub/issues/28
