### ISSUE TITLE
scrubbing of dedupe VDISK (means check disks are ok & remove old data)

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#71]
- dedupe VDISK needs the consumer references implemented
- each VDISK os a consumer of the deduped storage pool.
- there are reference lists (upto 10) which tells who is using a block.
- this needs to be implemented so delete can happen
- while scrubbing check that all required blocks are on the system (good for testing too)

**Comment by rkhamis** [comment]
Moved to https://github.com/zero-os/0-Disk/issues/436
