### ISSUE TITLE
update specs & docs

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#75]
- see spec & doc issues on multiple repo's
- requirements
    - right docs on right repo's
    - docs = implemented functionality
    - always under /docs
    - specs is still to be implemented
- make sure following is in
    - logging to redis inside zero-os (how, what, ...), put in zero-core repo

**Comment by zaibon** [comment]
link to docs regarding logging to redis in 0-core : https://github.com/zero-os/0-core/tree/master/docs/monitoring/logging.md and  https://github.com/zero-os/0-core/blob/master/docs/monitoring/stats.md
