### ISSUE TITLE
Zero-OS feedback mechanism

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#76]
see
- https://github.com/zero-os/0-orchestrator/blob/despiegk-specs/specs/feedback_mechanism_ays_service.md

standardised way of sending output & errorconditions to ays.

QUESTION:
- there seems to be a logging mechanism to Redis (rolling)
- maybe its better to keep on using Redis & use a queue per AYS server to see what is new & then get the info

**Comment by zaibon** [comment]
Zero-os now supports streaming of stdout and stderr back to the client.
So AYS can already watch and monitor the streams of a process.

>sends the stdout to orchestrator on url
/stdout/$actorname/$serviceinstancename
/stderr/$actorname/$serviceinstancename

This needs to be more defined. What should this endpoint return ? All the output from the begining of the process ? only last part of it ? what about long running processes that generate a lot of logs?
