### ISSUE TITLE
FR: How to avoid Mac Address conflicts and maintain the list

### ISSUE THREAD

**Issue by arnevanbalgoijen** [zero-os/home#77]
Every instance of Zero-OS and Containers & VMs requires a new unique mac address. Is there now way to auto generate these just like/based on the unique nodeID?
Docker instances seem to use the vendor code 02:42:ac as the first part of the Mac Address, maybe for Zero-OS a vendor code can be claimed.

**Comment by grimpy** [comment]
Zero-OS provides and API to allow you to choose your own range, products integrating with Zero-OS are supposed to manage those. 

It's also possible to just ommit the Mac-Address which means kvm, linux kernel will autoassign a MAC-Address
