### ISSUE TITLE
FR: Why use ZeroTier if every Zero-OS node could use IPv6 with authentication & IPSEC?

### ISSUE THREAD

**Issue by arnevanbalgoijen** [zero-os/home#78]
Currently for the management of Zero-OS nodes in a grid a ZeroTier network is in use. ZeroTier uses its own authentication and offers API access using a shared secret. Would it not be simpler and more secure to use IPv6 and its security features instead? And if so could itsyou.online not act as the means to organize & manage secure communication between systems.

**Comment by despiegk** [comment]
sorry for the late reply.
we are now first focussed on launching our first release, which is over the next weeks.

we believe zero-tier is a very simple product and makes it easy for people to use anywhere it can easily cross any nat gateway and the API's are good.

we want to support IPSEC too but this is for future
