### ISSUE TITLE
measurement tool for any HW node

### ISSUE THREAD

**Issue by despiegk** [zero-os/home#84]
see Christophe, he has prototype

test on multiple hardware's to see we have output

minimal requirements
- cpu (id & size) (type/speed)
- memory size
- motherboard id
- ssd/hd id/size (type/speed)

put all in nicely formatted dict

run inside python sandbox using our flist & sb tool

**Comment by zaibon** [comment]
Test of the capacity report on 2 type of 0-os node, see https://github.com/zero-os/home/issues/88#issuecomment-376920748 We should still test it on some more hardware
