### ISSUE TITLE
Test the capacity check on different hardware configuration

### ISSUE THREAD

**Issue by zaibon** [zero-os/home#88]
We need to check and test the report generated for different hardware:
- tft node
- converged server (Like the one in Dubai and Belgium farm)
- storage box
- ...

**Comment by chrisvdg** [comment]
Current reports 
* Small TFT node: https://gist.github.com/chrisvdg/1c648cf5dc3edf4b52a690e17cc74e4f#file-tf_node-json
* BT node (2u server): https://gist.github.com/chrisvdg/1c648cf5dc3edf4b52a690e17cc74e4f#file-bt_node

**Comment by zaibon** [comment]
In TFT node, the ressource unit computed are not correct, I see 0 SRU while the report clearly shows some SSD, same for HRU

**Comment by zaibon** [comment]
On BT node, clearly something wrong since we don't have any hardware info

**Comment by chrisvdg** [comment]
> In TFT node, the ressource unit computed are not correct, I see 0 SRU while the report clearly shows some SSD, same for HRU

It shows 0 no matter where the capacity report is called on, will look into it
