### ISSUE TITLE
How to set up a wallet

### ISSUE THREAD

**Issue by raetser** [zero-os/home#92]
I am trying to follow the setup guide for farmers, and when I need to fill in the form I need a wallet address, but how do I get a wallet?
I currently have my personal wallet in the ThreeFold app, but I want to use another address for the farmer stuff...
I can only find a wallet script for Linux, what are the options here?
For testing purpose I will use my personal address..

**Comment by zaibon** [comment]
The wallet is not a required field for registration, so you can omit it if needed.
Regarding how to get a wallet, this is out of scope here, but you should have all the information there: https://github.com/threefoldfoundation/tfchain the official repo for the TFT wallet

**Comment by raetser** [comment]
Christophe,
I have managed to add my capacity to the grid using the doc steps, but what the registered info shows is unclear to me:
![image](https://user-images.githubusercontent.com/10166396/40359036-9634a7e8-5dc1-11e8-8356-6d10577244a4.png)
CPU is correct, being 2 CPU per machine with dual 10 core = 40 Cores
RAM is correct as well, 128 Gb and 386 Gb
HRU should be Hard Disk, right? One server has 112 TB, the other one 72 TB, I don't see any correlated data...
SRU is SSD I guess, I have 2 x 1TB in one server, 2x2TB in the other one, but the data says 0 on both servers...

**Comment by zaibon** [comment]
Regarding the SRU, this is a known bug. Will be fix in the current of the week.
But for your HDD, this could show that some of your disk are not recognized as HDD for some reason.
If you want, you can restart one of the node with the `development` kernel flag, and ping me so I can investigate more in detail

**Comment by zaibon** [comment]
So turned out if was a problem with the raid controller of the nodes.
The raid controller required that a virtual disk was created on top of each disk.
Once this done, 0-OS detects the disks properly

**Comment by raetser** [comment]
Indeed, problem solve. Capacity shows up on the capacity website ( apart from the SSD as Christophe mentioned)
Case closed :-)
